algoritmo "semnome"
// Função :
// Autor :
// Data : 24/02/2022
var
nota1:inteiro
nota2:inteiro
nota3:inteiro
nota4:inteiro
soma:inteiro
result:inteiro
inicio
Escreva("informe a nota do 1ºB: ")
leia(nota1)
escreva("do 2ºB: ")
leia(nota2)
escreva("do 3ºB: ")
leia(nota3)
escreva("do 4ºB: ")
leia(nota4)
soma<-nota1+nota2+nota3+nota4
result<-soma*4
escreva("a media é: ", result)
leia(result)
fimalgoritmo
